import type { Role } from '@/shared/types/domain';

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  PRODUCTION_ORDERS_VIEW: 'production-orders:view',
  PRODUCTION_ORDERS_CREATE: 'production-orders:create',
  PRODUCTION_ORDERS_MANAGE: 'production-orders:manage',
  PRODUCTION_ORDER_ATTACHMENTS_VIEW: 'production-orders:attachments:view',
  PRODUCTION_ORDERS_INCOMING: 'production-orders:incoming',
  PRODUCTION_ORDERS_UNIT_TASK: 'production-orders:unit-task',
  ADMIN_USERS_VIEW: 'admin:users:view',
  ADMIN_USERS_CREATE: 'admin:users:create',
  ADMIN_USERS_UPDATE: 'admin:users:update',
  ADMIN_USERS_RESET_PASSWORD: 'admin:users:reset-password',
  ADMIN_USERS_DELETE: 'admin:users:delete'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_DEFAULT_PERMISSIONS: Record<Role, PermissionCode[]> = {
  admin: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_MANAGE,
    PERMISSIONS.PRODUCTION_ORDER_ATTACHMENTS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_INCOMING,
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK,
    PERMISSIONS.ADMIN_USERS_VIEW,
    PERMISSIONS.ADMIN_USERS_CREATE,
    PERMISSIONS.ADMIN_USERS_UPDATE,
    PERMISSIONS.ADMIN_USERS_RESET_PASSWORD,
    PERMISSIONS.ADMIN_USERS_DELETE
  ],
  production_manager: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_MANAGE,
    PERMISSIONS.PRODUCTION_ORDER_ATTACHMENTS_VIEW
  ],
  raw_preparation: [
    PERMISSIONS.PRODUCTION_ORDER_ATTACHMENTS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_INCOMING,
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK
  ],
  machine_operator: [
    PERMISSIONS.PRODUCTION_ORDERS_INCOMING,
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK
  ]
};
