import type { Role } from '@/shared/types/domain';

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  STOCKS_VIEW: 'stocks:view',
  STOCKS_CREATE: 'stocks:create',
  PRODUCTION_ORDERS_VIEW: 'production-orders:view',
  PRODUCTION_ORDERS_CREATE: 'production-orders:create',
  PRODUCTION_ORDERS_DELETE: 'production-orders:delete',
  PRODUCTION_ORDERS_WAREHOUSE: 'production-orders:warehouse',
  PRODUCTION_ORDERS_MONITOR: 'production-orders:monitor',
  PRODUCTION_ORDERS_UNIT_TASK: 'production-orders:unit-task',
  ADMIN_USERS_VIEW: 'admin:users:view',
  ADMIN_USERS_CREATE: 'admin:users:create',
  ADMIN_USERS_UPDATE: 'admin:users:update',
  ADMIN_USERS_RESET_PASSWORD: 'admin:users:reset-password',
  ADMIN_USERS_DELETE: 'admin:users:delete'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_DEFAULT_PERMISSIONS: Record<Role, PermissionCode[]> = {
  admin: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCKS_VIEW,
    PERMISSIONS.STOCKS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_DELETE,
    PERMISSIONS.PRODUCTION_ORDERS_WAREHOUSE,
    PERMISSIONS.PRODUCTION_ORDERS_MONITOR,
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK,
    PERMISSIONS.ADMIN_USERS_VIEW,
    PERMISSIONS.ADMIN_USERS_CREATE,
    PERMISSIONS.ADMIN_USERS_UPDATE,
    PERMISSIONS.ADMIN_USERS_RESET_PASSWORD,
    PERMISSIONS.ADMIN_USERS_DELETE
  ],
  production_manager: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCKS_VIEW,
    PERMISSIONS.STOCKS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_DELETE,
    PERMISSIONS.PRODUCTION_ORDERS_MONITOR
  ],
  warehouse_manager: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCKS_VIEW,
    PERMISSIONS.STOCKS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_VIEW,
    PERMISSIONS.PRODUCTION_ORDERS_CREATE,
    PERMISSIONS.PRODUCTION_ORDERS_DELETE,
    PERMISSIONS.PRODUCTION_ORDERS_WAREHOUSE
  ],
  hat: [
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK
  ],
  tablet1: [
    PERMISSIONS.PRODUCTION_ORDERS_UNIT_TASK
  ]
};
